### ISSUE TITLE
Does not work well with newest json-ptr (1.3.1)

### ISSUE THREAD

**Issue by psznm** [exegesis-js/exegesis#146]
New version of json-ptr was published 2 days ago (2020-07-12) and broke exegesis.

TypeError: jsonPtr.decode is not a function

When downgraded json-ptr to 1.2.0 everything works OK. I can not give much more detail as I do not have great understanding of the whole system and how exegesis is used in it.

**Comment by psznm** [comment]
at resolveRefPriv (.../node_modules/exegesis/src/utils/json-schema-resolve-ref.ts:8:26)
 at resolveRef (.../node_modules/exegesis/src/utils/json-schema-resolve-ref.ts:25:16)
 at extractSchemaPriv (.../node_modules/exegesis/src/utils/jsonSchema.ts:22:27)
 at Object.extractSchema (.../node_modules/exegesis/src/utils/jsonSchema.ts:114:12)
 at generateValidator (.../node_modules/exegesis/src/oas3/Schema/validators.ts:194:34)
 at Object.generateResponseValidator (.../node_modules/exegesis/src/oas3/Schema/validators.ts:256:12)
 at new Responses (.../node_modules/exegesis/src/oas3/Response.ts:31:33)
 at new Responses (.../node_modules/exegesis/src/oas3/Responses.ts:22:43)
 at new Operation (.../node_modules/exegesis/src/oas3/Operation.ts:133:27)
 at Path._operations.HTTP_METHODS.map.filter.reduce (.../node_modules/exegesis/src/oas3/Path.ts:39:34)|
